language: cpp
compiler:
  - gcc
  - clang

#sudo: false
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libeigen3-dev
    - gcc-4.9
    - g++-4.9
    - clang

before_install:
  - ${CXX} --version;
  - cmake --version;

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - cmake .
  - make VERBOSE=1

script: 
  - echo ${CXX}
  - make test
